networks:
  law-network:
    internal: false


services:
  law-mysql:
    image: mysql:8.4
    container_name: law-mysql
    hostname: law-mysql
    ports:
      - "3306:3306"
    networks:
      - law-network
    environment:
      LANG: C.UTF-8 # 中文乱码-1
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./law-data:/var/lib/mysql-files
      - ./static:/docker-entrypoint-initdb.d/
    # 中文乱码-2
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--secure-file-priv=/var/lib/mysql-files']
