networks:
  law-network:
    internal: false


services:
  law-mysql:
    image: mysql:8.4
    container_name: law-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: law
      MYSQL_USER: law
      MYSQL_PASSWORD: law
    ports:
      - "3306:3306"
    networks:
      - law-network
