CREATE DATABASE IF NOT EXISTS `bank`;

USE bank;

DROP TABLE IF EXISTS `account`;
CREATE TABLE `account` (
  `账户开户名称` VARCHAR(100) DEFAULT NULL COMMENT '账户开户名称',
  `开户人证件号码` VARCHAR(50) DEFAULT NULL COMMENT '开户人证件号码',
  `交易卡号` VARCHAR(50) DEFAULT NULL COMMENT '交易卡号',
  `交易账号` VARCHAR(50) DEFAULT NULL COMMENT '交易账号',
  `账号开户时间` VARCHAR(50) DEFAULT NULL COMMENT '账号开户时间',
  `账户余额` DECIMAL(18, 2) DEFAULT NULL COMMENT '账户余额',
  `可用余额` DECIMAL(18, 2) DEFAULT NULL COMMENT '可用余额',
  `币种` VARCHAR(10) DEFAULT NULL COMMENT '币种',
  `开户网点代码` VARCHAR(50) DEFAULT NULL COMMENT '开户网点代码',
  `开户网点` VARCHAR(100) DEFAULT NULL COMMENT '开户网点',
  `账户状态` VARCHAR(50) DEFAULT NULL COMMENT '账户状态',
  `炒汇标志名称` VARCHAR(50) DEFAULT NULL COMMENT '炒汇标志名称',
  `销户日期` VARCHAR(50) DEFAULT NULL COMMENT '销户日期',
  `账户类型` VARCHAR(50) DEFAULT NULL COMMENT '账户类型',
  `开户联系方式` VARCHAR(100) DEFAULT NULL COMMENT '开户联系方式',
  `通信地址` VARCHAR(200) DEFAULT NULL COMMENT '通信地址',
  `联系电话` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `代理人` VARCHAR(100) DEFAULT NULL COMMENT '代理人',
  `代理人电话` VARCHAR(20) DEFAULT NULL COMMENT '代理人电话',
  `备注` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `开户省份` VARCHAR(50) DEFAULT NULL COMMENT '开户省份',
  `开户城市` VARCHAR(50) DEFAULT NULL COMMENT '开户城市',
  `账号开户银行` VARCHAR(100) DEFAULT NULL COMMENT '账号开户银行',
  `客户代码` VARCHAR(50) DEFAULT NULL COMMENT '客户代码',
  `法人代表` VARCHAR(100) DEFAULT NULL COMMENT '法人代表',
  `客户工商执照号码` VARCHAR(50) DEFAULT NULL COMMENT '客户工商执照号码',
  `法人代表证件号码` VARCHAR(50) DEFAULT NULL COMMENT '法人代表证件号码',
  `住宅地址` VARCHAR(200) DEFAULT NULL COMMENT '住宅地址',
  `邮政编码` VARCHAR(10) DEFAULT NULL COMMENT '邮政编码',
  `代办人证件号码` VARCHAR(50) DEFAULT NULL COMMENT '代办人证件号码',
  `邮箱地址` VARCHAR(100) DEFAULT NULL COMMENT '邮箱地址',
  `关联资金账户` VARCHAR(50) DEFAULT NULL COMMENT '关联资金账户',
  `地税纳税号` VARCHAR(50) DEFAULT NULL COMMENT '地税纳税号',
  `单位电话` VARCHAR(20) DEFAULT NULL COMMENT '单位电话',
  `代办人证件类型` VARCHAR(50) DEFAULT NULL COMMENT '代办人证件类型',
  `住宅电话` VARCHAR(20) DEFAULT NULL COMMENT '住宅电话',
  `法人代表证件类型` VARCHAR(50) DEFAULT NULL COMMENT '法人代表证件类型',
  `国税纳税号` VARCHAR(50) DEFAULT NULL COMMENT '国税纳税号',
  `单位地址` VARCHAR(200) DEFAULT NULL COMMENT '单位地址',
  `工作单位` VARCHAR(100) DEFAULT NULL COMMENT '工作单位',
  `销户网点` VARCHAR(100) DEFAULT NULL COMMENT '销户网点',
  `最后交易时间` VARCHAR(50) DEFAULT NULL COMMENT '最后交易时间',
  `账户销户银行` VARCHAR(100) DEFAULT NULL COMMENT '账户销户银行'
#   PRIMARY KEY (`交易账号`) -- 假设交易账号是唯一标识
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账户信息表';

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/中国银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/农业银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/四川农信_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/工商银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/建设银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/民生银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/工商银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/泰隆银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/浦发银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第一批流水/邮政储蓄银行_银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第二批流水/银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第三批流水/银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第四批流水/银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第五批流水/银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/var/lib/mysql-files/第七批流水/银行账户.csv'
INTO TABLE account
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
